language: python
sudo: required
dist: trusty
group: deprecated-2017Q2

services:
- docker

script:
- sudo apt-get update
- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
- pip install --upgrade setuptools # bug fix http://j.mp/2v9Hs98
- pip install --upgrade -r dev-requirements.txt
- pip3 install --upgrade --no-cache-dir --editable .
- rapydo --version
- rapydo --help
- git clone https://github.com/rapydo/tests.git rapydo_tests
# - BRANCH=`[ TRAVIS_PULL_REQUEST ] && echo $TRAVIS_PULL_REQUEST_BRANCH || echo $TRAVIS_BRANCH`
- BRANCH=`[  -z "$TRAVIS_PULL_REQUEST_BRANCH" ] && echo "$TRAVIS_BRANCH" || echo "$TRAVIS_PULL_REQUEST_BRANCH"`
# - echo "TRAVIS_PULL_REQUEST = ${TRAVIS_PULL_REQUEST}"
# - echo "TRAVIS_PULL_REQUEST_BRANCH = ${TRAVIS_PULL_REQUEST_BRANCH}"
# - echo "TRAVIS_BRANCH = ${TRAVIS_BRANCH}"
- echo "BRANCH = ${BRANCH}"
- cd rapydo_tests
- git checkout $BRANCH
- mkdir data
- TESTING=1 py.test -s -x --cov=controller ../tests
after_success:
- coveralls
- pwd

jobs:
  include:
    - stage: test
      python: 3.4
    - python: 3.5
    - python: 3.6.2

    - stage: deploy
      python: 3.6.2
      script: skip
      deploy:
        provider: pypi
        user: pdonorio
        password:
          secure: t5rXTrlqnR1De/rsfO4eDTyRz6e+osTnwLqkphwJ1JQzWh3n5lA2ZYYO6Vmil2oj3X+fFOuhMMnu/QGFwdYP+Hp1EPxecj2WnBKxkW8PtC20w0oAmxFg09teRq/RBbtHs+z/NGGYmWr7V0Ic5iQt53iTX4eBb6LhQ9aLHg05+SsJDAgniKQzpOtt72m+ZYECv86xIr3q5SIl+k0os1VwJtbAqJRMRigvPP05X0ufrTq/uCyHF9EEKOtvVdgYGfiFdOFh5URSfHaV4ASNNGEsU+l3Twfhk6wqQQkvSHeZy0onY90KnCLj7sl3bTyeo6wBPG5jGV/zYhHhZgWyLJI5hZk426oIvkZ0Tj6TxsZNUDNSHNhPgKuR6tEnEt0BGd4oL3YpAKzQmFWMfwzn0UF/CPhpF5gNxWbhfO/+yfxvPfw1QvrVHb9O5hXji8U1q2a+W9dqIAAxKnH0hZZLSQcCihSBTU4oh1lJXqG+Rzo3hLb8XtMEQjMIcx5f4zPf+unRqPWe6ViMZ0eikqmA6lniKMPnqk457fyxzLoda4iaSvSqMxByGx0DSqURIcU87ejKzI+TrZh+I3hqU2SK1yN79kTJ9wFnjKL+2OMjBhIIjUDa5tNf0RauNbCNyuTv2z947PMsJGEZRX4pGR29lwMLnQH3gVcrQ2eJTlxl5x4iEKo=
        on:
          tags: true
